name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

  setup-dotnet:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

  restore-dependencies:
    runs-on: ubuntu-latest
    needs: setup-dotnet
    steps:
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./FitFusion/FitFusionTest

  build:
    runs-on: ubuntu-latest
    needs: restore-dependencies
    steps:
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./FitFusion

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter FullyQualifiedName~FitFusionTest
      working-directory: ./FitFusion/FitFusionTest
